#!/bin/bash

TEMPLATE_FILES_CREATION_DATE="30\/07\/21"
PROJECT_NAME="Project"

while [[ $# -gt 0 ]]
do
    key="$1"

    case $key in
        -n|--name)
            PROJECT_NAME="$2"
            shift
            shift
            ;;
        --help)
            echo "Initial setup script for Xcode project template"
            echo
            echo
            echo " --name       New project name"
            echo
            echo " --help       Show this help message and exit"
            exit
            ;;
        *)
            echo "$1 is not a valid option."
            exit
            ;;
    esac
done


while true; do
    read -p "Choose framework [UIKit/SwiftUI]: " yn
    case $yn in
        [Uu][Ii][Kk][Ii][Tt]) rm -rf App/SwiftUI ; mv App/UIKit App/Project ; break ;;
        [Ss][Ww][Ii][Ff][Tt][Uu][Ii]) rm -rf App/UIKit ; mv App/SwiftUI App/Project break ;;
    esac
done

ls Makefile App/Podfile App/*.yml config/*.yml | xargs sed -i '' "s/PROJECT_NAME/${PROJECT_NAME}/g"
find -E App/Project -type f -regex '.*\.(swift|strings)' | xargs sed -i '' "s/PROJECT_NAME/${PROJECT_NAME}/g"
find -E App/Project -type f -regex '.*\.(swift|strings)' | xargs sed -i '' "s/${TEMPLATE_FILES_CREATION_DATE}/$(date '+%d\/%m\/%y')/g"
mv App/Project App/$PROJECT_NAME
echo "# $PROJECT_NAME" > README.md
make generate
rm -rf .git
git init
rm init
