name: PROJECT_NAME

settings:
  DEVELOPMENT_TEAM: H7BM7N56V5

options:
  bundleIdPrefix: com.vcoutasso
  deploymentTarget:
    iOOS: 14.0

targets:
  PROJECT_NAME:
    type: application
    platform: iOS
    sources:
      - path: PROJECT_NAME
    preBuildScripts:
      - name: SwiftLint
        script: |
          "${PODS_ROOT}/SwiftLint/swiftlint"
      - name: SwiftGen
        script: |
          "${PODS_ROOT}/SwiftGen/bin/swiftgen"

